from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^$', login_required(views.IndexView.as_view()), name='index'),
    url(r'^create/$', login_required(views.audit_create), name='audit_create'),
    url(r'^audit/(?P<audit_id>[0-9]+)/$', login_required(views.audit),
         name='audit'),
    url(r'^audit/process/create$', login_required(views.process),
         name='process_create'),
    url(r'^audit/process/(?P<process_id>[0-9]+)$',
         login_required(views.process), name='audit_process'),
    url(r'^audit/objective/create$', login_required(views.objective),
         name='objective_create'),
    url(r'^audit/objective/(?P<objective_id>[0-9]+)$',
         login_required(views.objective), name='audit_objective'),
    url(r'^not_implemented$', login_required(views.not_implemented),
         name='not_implemented'),


    url(r'^audit/risk/create$', login_required(views.risk), name='risk_create'),
    url(r'^audit/risk/(?P<risk_id>[0-9]+)$', login_required(views.risk),
         name='audit_risk'),
    url(r'^audit/(?P<audit_id>[0-9]+)/control/create$',
         login_required(views.control_create), name='control_create'),
    url(r'^audit/control/(?P<control_id>[0-9]+)$',
         login_required(views.control), name='audit_control'),
    url(r'^audit/(?P<audit_id>[0-9]+)/execute/(?P<view_type>process|objective|risk|control|test)$',
         login_required(views.AuditExecuteView.as_view()),
          name='audit_execute'),
    url(r'^audit/process/(?P<process_id>[0-9]+)/objective$',
         login_required(views.process_objective),
          name='audit_process_objective'),
    url(r'^audit/objective/(?P<objective_id>[0-9]+)/risks$',
         login_required(views.objective_risk), name='audit_objective_risk'),
    url(r'^audit/risk/(?P<risk_id>[0-9]+)/controller$',
         login_required(views.risk_controller), name='audit_risk_controller'),
    url(r'^audit/control/(?P<control_id>[0-9]+)/test$',
         login_required(views.controller_test), name='audit_controller_test'),
    url(r'^audit/test/(?P<test_id>[0-9]+)/findings$',
         login_required(views.test_findings), name='audit_test_findings'),
    url(r'^audit/test/(?P<test_id>[0-9]+)/ajax$',
         login_required(views.AjaxTestResultView.as_view()),
         name='audit_ajax_test_form'),
    url(r'^audit/finding/ajax-add$',
         login_required(views.AjaxFindingView.as_view()),
         name='ajax_finding_view'),
    url(r'^attachment/(?P<attachment_id>[0-9]+)/delete$',
         login_required(views.AjaxAttachmentDeleteView.as_view()),
         name='ajax_attachment_delete'),
    url(r'^audit/(?P<audit_id>[0-9]+)/management/$',
         login_required(views.AuditChildView.as_view()),
          name='audit_management'),
    # Process Management
    url(r'^audit/(?P<audit_id>[0-9]+)/process/add$',
         login_required(views.AjaxProcessAddEditView.as_view()),
         name='ajax_process_add'),
    url(r'^audit/(?P<audit_id>[0-9]+)/process/(?P<process_id>[0-9]+)/edit$',
         login_required(views.AjaxProcessAddEditView.as_view()),
         name='ajax_process_edit'),
    url(r'^process/(?P<process_id>[0-9]+)/delete$',
         login_required(views.AjaxProcessDeleteView.as_view()),
         name='ajax_process_delete'),
    #Objective Management
    url(r'^audit/(?P<audit_id>[0-9]+)/objective/add$',
         login_required(views.AjaxObjectiveAddEditView.as_view()),
         name='ajax_objective_add'),
    url(r'^audit/(?P<audit_id>[0-9]+)/objective/(?P<objective_id>[0-9]+)/edit$',
         login_required(views.AjaxObjectiveAddEditView.as_view()),
         name='ajax_process_edit'),
    url(r'^objective/(?P<objective_id>[0-9]+)/delete$',
         views.AjaxObjectiveDeleteView.as_view(),
         name='ajax_objective_delete'),
    #Risk Management
    url(r'^audit/(?P<audit_id>[0-9]+)/risk/add$',
         login_required(views.AjaxRiskAddEditView.as_view()),
         name='ajax_risk_add'),
    url(r'^audit/(?P<audit_id>[0-9]+)/risk/(?P<risk_id>[0-9]+)/edit$',
         login_required(views.AjaxRiskAddEditView.as_view()),
         name='ajax_risk_edit'),
    url(r'^risk/(?P<risk_id>[0-9]+)/delete$',
         login_required(views.AjaxRiskDeleteView.as_view()),
         name='ajax_risk_delete'),
    #Control Management
    url(r'^audit/(?P<audit_id>[0-9]+)/control/add$',
         login_required(views.AjaxControlAddEditView.as_view()),
         name='ajax_control_add'),
    url(r'^audit/(?P<audit_id>[0-9]+)/control/(?P<control_id>[0-9]+)/edit$',
         login_required(views.AjaxControlAddEditView.as_view()),
         name='ajax_control_edit'),
    url(r'^control/(?P<control_id>[0-9]+)/delete$',
         login_required(views.AjaxControlDeleteView.as_view()),
         name='ajax_control_delete'),
    #Test Management
    url(r'^audit/(?P<audit_id>[0-9]+)/test/add$',
         login_required(views.AjaxTestAddEditView.as_view()),
         name='ajax_test_add'),
    url(r'^audit/(?P<audit_id>[0-9]+)/test/(?P<test_id>[0-9]+)/edit$',
         login_required(views.AjaxTestAddEditView.as_view()),
         name='ajax_test_edit'),
    url(r'^test/(?P<test_id>[0-9]+)/delete$',
         login_required(views.AjaxTestDeleteView.as_view()),
         name='ajax_test_delete'),
    #Report Generation
    url(r'^audit/(?P<pk>[0-9]+)/report$',
         login_required(views.AuditReport.as_view()),
         name='audit_report'),
]