# Generated by Django 2.1.4 on 2018-12-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='ref_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='reference ID'),
        ),
        migrations.AddField(
            model_name='objective',
            name='ref_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='reference ID'),
        ),
        migrations.AddField(
            model_name='process',
            name='ref_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='reference ID'),
        ),
        migrations.AddField(
            model_name='risk',
            name='ref_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='reference ID'),
        ),
        migrations.AddField(
            model_name='test',
            name='ref_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='reference ID'),
        ),
    ]
